--- 
backend: 
  branch: master
  name: github
  repo: stevemoser/jekyll-netlify-cms
collections: 
  - 
    create: true
    fields: 
      - 
        default: post
        label: Layout
        name: layout
        widget: hidden
      - 
        label: Title
        name: title
        tagname: h1
        widget: string
      - 
        label: Body
        name: body
        widget: markdown
      - 
        label: Categories
        name: categories
        widget: string
    folder: _posts
    label: Post
    meta: 
      - 
        format: "YYYY-MM-DD hh:mm:ss"
        label: "Publish Date"
        name: date
        widget: datetime
    name: post
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
media_folder: img/uploads
