--- 
backend:
  name: git-gateway
  branch: source # Branch to update (optional; defaults to master)
  publish_mode: editorial_workflow
  media_folder: "/images" # Media files will be stored in the repo under static/images/uploads
  public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections: 
  - 
    create: true
    fields: 
      - 
        default: post
        label: Layout
        name: layout
        widget: hidden
      - 
        label: Title
        name: title
        tagname: h1
        widget: string
      - 
        label: Body
        name: body
        widget: markdown
      - 
        label: Categories
        name: categories
        widget: string
    folder: _posts
    label: Post
    meta: 
      - 
        format: "YYYY-MM-DD hh:mm:ss"
        label: "Publish Date"
        name: date
        widget: datetime
    name: post
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
media_folder: img/uploads
